version: "3"
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
  app:
    build: .
    ports:
      - 8080:8080
    links:
      - mongodb