AWSTemplateFormatVersion: '2010-09-09'
Description: Your First DynamoDB Table

Parameters:
  TableName:
    Description: 'Table Name'
    Type: String

Resources:
  DemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  TableName:
    Value: !GetAtt 'DemoTable.Arn'
    Description: For demo api
    Export:
      Name: 'DemoTable'